### ISSUE TITLE
d3dx9_43.dll file is missing

### ISSUE THREAD

**Issue by rvokes** [FishPhd/DewritoUpdater#28]
Title says it all. Any idea what's going on? I downloaded everything you posted on youtube, extracted the 2gb halo file and updated Halo Online to v0.4.11.2 and it says it's missing d3dx9_43.dll.

**Comment by twist84** [comment]
You need to install the redistibutables which will be in halo\tpi\ install directx\directx_june2010.exe and vc2012_redist\vcredist_x86.exe.

I might add that this problem has nothing at all to do with the updater, its due to human error (Basically you're a dumb dumb who didn't read the guide properly if not at all).

READ THE GUIDE THOROUGHLY https://blam.halo.click/5402Jy.pdf
